var translate_columns = {
  "name": "昵称",
  "url_token": "用户识别码",
  "user_type": "用户类型",
  "avatar_url": "头像链接",
  "business": "所属领域",
  "description": "个人描述",
  "educations": "教育背景",
  "employments": "职业背景",
  "gender": "性别",
  "headline": "签名",
  "locations": "地区",
  "answer_count": "回答数",
  "articles_count": "文章数",
  "voteup_count": "获赞数",
  "thanked_count": "感谢数",
  "favorited_count": "收藏数",
  "follower_count": "被关注数",
  "following_count": "关注数",
};
var en_columns = [
  "name",
  "url_token",
  "user_type",
  "avatar_url",
  "business",
  "description",
  "educations",
  "employments",
  "gender",
  "headline",
  "locations",
  "answer_count",
  "articles_count",
  "voteup_count",
  "thanked_count",
  "favorited_count",
  "follower_count",
  "following_count",
];